# build this from vars until we can get cluster_url and ServiceInstance UID
params_string: "{{ namespace }}::{{ _apb_plan_id }}::{{ aws_access_key }}::{{ aws_secret_key }}::{{ aws_cloudformation_role_arn }}::{{ KeyName }}::{{ region }}::{{ EMRApplication }}::{{ ReleaseLabel }}::{{ MasterInstanceType }}::{{ CoreInstanceType }}::{{ NumberOfCoreInstances }}::{{ VpcId }}"
params_hash: "{{ params_string | checksum }}"
application_name_alnum: "{{ application_name | regex_replace('[^a-zA-Z0-9]') }}"

# params
EMRClusterName: "{{ application_name_alnum }}-{{ lookup('password', '/dev/null chars=ascii_letters,digits length=8') }}"
EMRCidr: "auto"

# We should probably be generating a keypair here and returning the privatekey as a secret