- name: Launch EMR cluster
  cloudformation:
   aws_access_key: "{{ aws_access_key }}"
   aws_secret_key: "{{ aws_secret_key }}"
   stack_name: "apb-RDS-{{ stack_identifier }}"
   state: "present"
   region: "{{ region }}"
   disable_rollback: false
   template: "{{ role_path }}/files/emrcluster.yml"
   template_parameters:
     Applications: "{{ Applications }}"
     EMRClusterName: "{{ EMRClusterName }}"
     KeyName: "{{ KeyName}}"
     MasterInstanceType: "{{ MasterInstanceType }}"
     CoreInstanceType: "{{ CoreInstanceType }}"
     NumberOfCoreInstances: "{{ NumberOfCoreInstances }}"
     SubnetID: "{{SubnetID }}"
     LogUri: "{{LogUri}}"
     S3DataUri: "{{ S3DataUri }}"
     ReleaseLabel: "{{ ReleaseLabel }}"
   tags:
     Stack: "ansible-cloudformation"
     Application: "ansible-emr"
     Description: "{{ ansible_user_id }} EMR {{ ApplicationName }}"
  register: emr
