global:
  parameters: {}
  regions:
    - us-east-1

plans:
  emr-prod:
    parameters:
      EMRApplication: Spark
      ReleaseLabel: emr-5.7.0
      MasterInstanceType: m4.xlarge
      CoreInstanceType: m4.xlarge
      NumberOfCoreInstances: 2
    sample_app: emr-sample-app-apb