#############################################################################
# Deprovision EMR service
#############################################################################

- name: Remove EMR cluster
  cloudformation:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    stack_name: "apb-emr-{{ stack_identifier }}"
    state: "absent"
    region: "{{ region }}"
