#############################################################################
# Deprovision EMR service
#############################################################################

- name: Remove EMR cluster
  cloudformation:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    stack_name: "apb-emr-{{ stack_suffix }}"
    state: "absent"
    region: "{{ region }}"
- name: Remove IAM policy
  iam_policy:
    iam_type: user
    iam_name: "apb-emr-iam-{{ stack_suffix }}"
    policy_name: "EMR-APB-{{ stack_suffix }}"
    state: absent
- name: Remove IAM user
  iam:
    iam_type: user
    name: "apb-emr-iam-{{ stack_suffix }}"
    state: absent